### ISSUE TITLE
daemon.js spewing null-value errors to journal (by the thousands)

### ISSUE THREAD

**Issue by ferdnyc** [andyholmes/gnome-shell-extension-gsconnect#11]
<h3>Update</h3>

I've determined that the source of the problems could be caused by inadvertent local changes to `folks-cache.py` (see followup comment below), so please ignore this for right now while I revert those.

<h3>Original Report</h3>

Yikes. One of my two devices wasn't showing status in the User Menu even though it was on the network, so I went looking for error output in the journal only to discover these messages being output, in bursts, at the rate of _many_ per second:
```
Dec 01 02:54:45 teevey gjs[9775]: JS ERROR: TypeError: this.model.get_value(...) is null
                                  ContactCompletion<._match@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/telephony.js:184:20
                                  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
                                  ContactCompletion<._add@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/telephony.js:177:1
                                  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
                                  ContactCompletion<._populate@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/telephony.js:150:13
                                  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
                                  ContactCompletion<._init/<@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/telephony.js:140:13
                                  ContactsCache<._init/<@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/telephony.js:626:17
                                  @/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:653:2
Dec 01 02:54:45 teevey gjs[9775]: JS ERROR: TypeError: this.model.get_value(...) is null
                                  ContactCompletion<._match@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/telephony.js:184:20
                                  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
                                  ContactCompletion<._add@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/telephony.js:177:1
                                  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
                                  ContactCompletion<._populate@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/telephony.js:150:13
                                  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
                                  ContactCompletion<._init/<@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/telephony.js:140:13
                                  ContactsCache<._init/<@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/telephony.js:626:17
                                  @/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:653:2
Dec 01 02:54:45 teevey gjs[9775]: JS ERROR: TypeError: this.model.get_value(...) is null
                                  ContactCompletion<._match@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/telephony.js:184:20
                                  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
                                  ContactCompletion<._add@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/telephony.js:177:1
                                  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
                                  ContactCompletion<._populate@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/telephony.js:150:13
                                  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
                                  ContactCompletion<._init/<@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/telephony.js:140:13
                                  ContactsCache<._init/<@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/telephony.js:626:17
                                  @/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:653:2
Dec 01 02:54:45 teevey gjs[9775]: JS ERROR: TypeError: this.model.get_value(...) is null
                                  ContactCompletion<._match@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/telephony.js:184:20
                                  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
                                  ContactCompletion<._add@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/telephony.js:177:1
                                  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
                                  ContactCompletion<._populate@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/telephony.js:150:13
                                  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
                                  ContactCompletion<._init/<@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/telephony.js:140:13
                                  ContactsCache<._init/<@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/telephony.js:626:17
                                  @/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:653:2
```
In the three seconds from Dec 01 02:54:43 to Dec 01 02:54:45, `grep` counts 1204 instances of 'model.get_value', but none immediately before and none since then. (As I type this sentence it's now Dec 01 03:07 locally.) They seem to come in infrequent bursts, but every time they _do_ come it's a deluge. Here's a per-second count of the number of those messages logged, over the past 10k lines of my user journal:

```bash
% IFS="
"; for string in `journalctl --user -n 10000 |grep 'model.get_value' |cut -c1-15|uniq`; do echo -n "${string} - "; journalctl --user -n 10000 --no-pager |grep 'model.get_value' |grep -c "${string}"; done
Nov 30 21:01:22 - 201
Nov 30 21:01:23 - 402
Nov 30 21:01:24 - 601
Nov 30 21:39:00 - 157
Nov 30 21:39:01 - 231
Nov 30 21:39:02 - 215
Nov 30 21:39:03 - 517
Nov 30 21:39:04 - 84
Nov 30 22:42:18 - 247
Nov 30 22:42:19 - 481
Nov 30 22:42:20 - 476
Nov 30 23:39:13 - 201
Nov 30 23:39:14 - 561
Nov 30 23:39:15 - 442
Dec 01 00:53:52 - 36
Dec 01 00:53:53 - 354
Dec 01 00:53:54 - 641
Dec 01 00:53:55 - 173
Dec 01 01:42:12 - 380
Dec 01 01:42:13 - 635
Dec 01 01:42:14 - 189
Dec 01 02:13:14 - 146
Dec 01 02:13:15 - 508
Dec 01 02:13:16 - 550
Dec 01 02:54:43 - 352
Dec 01 02:54:44 - 413
Dec 01 02:54:45 - 439
```
Which, if you're playing along at home, means that 9,632 of the last 10,000 journal lines (96.3%) are that message. Or, going back farther, 18,431/20,000 (92.2%); 34,850/40,000 (87.1%); 44,346/50,000 (88.7%). Going back 50k lines only gets me as far as Nov 29 17:55:30 (a day and a half ago), and nowhere near the first instance of this issue. (Which _may_ be Nov 26, though I also found a single, solitary matching log message back on Nov 22. The `gjs` process hosting `daemon.js` with PID 9775 was started on Nov 24. So only that one solitary outlier predates the current process, and these massive bursts didn't start up until the current daemon process had been running for around two days. Curiouser and curiouser.)

Each spam-burst _looks_ to be preceded by this exact sequence. (That's based on a spot-check of two or three, I haven't examined every burst.) It always involves the same one of my two paired devices. (*Not* the one that isn't reporting correctly in the user menu, so that's probably completely unrelated and I'm not yet sure what the issue is there. But it makes sense that my phone 'lge' would be the device triggering this, as it's the only one for which the Telephony plugin is enabled. The other device is WiFi-only with no mobile service.)
```
Dec 01 02:54:34 teevey gjs[9775]: JS LOG: Failed to receive packet: Gio.TlsError: TLS connection closed unexpectedly
Dec 01 02:54:34 teevey gjs[9775]: JS LOG: Disconnected from 'lge'
Dec 01 02:54:41 teevey gjs[9775]: JS LOG: Daemon: Updating device
Dec 01 02:54:41 teevey gjs[9775]: JS LOG: Connecting to '${REDACTED}'
Dec 01 02:54:41 teevey gjs[9775]: JS LOG: Daemon: Updating device
Dec 01 02:54:42 teevey gjs[9775]: JS LOG: Authenticating '${REDACTED}'
Dec 01 02:54:42 teevey gjs[9775]: JS LOG: Connected to 'lge'
```
I'm still investigating here on my end, and will update if I come up with anything more to go on. For all the data I've spammed into this report (...revenge? 😉), I realize it's somewhat light on _useful_ info so far. I apologize for that, and will attempt to rectify it. But, any thoughts would be welcome!

**Comment by ferdnyc** [comment]
Oh,I should mention that I'm still running... for the most part your last zip from #8, I think. Though I now notice that my local copy is using the `folks-cache.py` changes I made (detailed in my last comment there), which differ from the commit you made to close the issue. I should try syncing those up. But, any local differences are confined to `folks-cache.py`, and all other files match the checked-in code. (Of course, `folks-cache.py` _could_ be involved here.)

Ooh, in **FAAACT**, I just discovered that `$HOME/.cache/gsconnect/contacts/` contains — among a surprising 2294 total files — several with creation dates that exactly match each of the daemon's journal-spew instance. So `folks-cache.py` is **definitely** involved. 

...Hmm, the dir contains exactly 23 such files, in fact. The same 23 files. Written out during each `folks-cache.py` run, with new random UUIDs.

It now appears that each time `folks-cache.py` is being run, on my system, it
1. retrieves the same 23 avatar images,
2. stores them in the cache directory with new random UUID names,
3. completely regenerates `contacts.json` with those new avatar file paths,
4. leaves all the previous files in place,
5. _and_ somehow triggers `daemon.js` to log thousands of null-value errors to the journal.

So, given the inconsistency between my local copy of the python code and the checked-in code, I'm going to say that this issue boils down to "something's up with `folks-cache.py`", and start by replacing my local copy with the repo HEAD so it's in a known state. These problems could very well be my own fault, so let's put this report on hold for the moment. I'd hate for you to go chasing a bug that's not even in your code.

**Comment by ferdnyc** [comment]
Hmm, I don't know if this should be closed just yet. I managed to trigger a new burst of these messages in the latest, greatest, #8-fixing code.

It turns out that they're caused by executing a manual `python3 folks-cache.py` while the GSConnect daemon is running. Now, maybe that's just a no-no and the simple solution is to say, "Don't do that." But since the daemon itself spawns `folks-cache.py` runs under certain cases, presumably it would still be causing the same problems for itself?

**Comment by ferdnyc** [comment]
(And when I say "a burst", I mean 400 messages in the space of a few seconds.)

**Comment by andyholmes** [comment]
It's hard to say, most of that affected code had been replaced with entirely different code now. Previously I had a `GtkEntryCompletion` model set to repopulate whenever the `contacts.json` file was changed on disk, but use a much more simplified approach on the widget side. I'm also planning to revisit the way the contacts are cached, but I'm not sure exactly what I'll be doing yet.

If you like you can use this ZIP which is up to date as of this morning:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/1525043/gsconnect.andyholmes.github.io.zip)

**Comment by andyholmes** [comment]
I'm going to assume this is fixed or invalidated since I don't use a `Gtk.EntryCompletion` or `Gtk.ListStore` for storing contacts anymore.

**Comment by ferdnyc** [comment]
Oops, sorry. I'd gotten busy with other things, and didn't have a chance to test the new zip until just now.

Looks like it has cleared up, yes — thanks! I almost reported that it _hadn't_, since I was still getting those messages by the hundred after running `python3 folks-cache.py`, but then I noticed that the `daemon.js` process on my machine was two days old. Seems even turning off the extension, completely replacing the directory, and restarting gnome-shell (I'm still running Xorg; Nvidia proprietary drivers) wasn't enough to kill it off. It's certainly resilient, I'll give it that! Once I manually killed the process, it respawned with the new code.

So far everything here looks good, along with another issue I'd been dragging my feet on reporting (since I knew the code was in flux and I wasn't current) where SMS replies weren't being directed to already-open conversation windows. But that's no longer the case, which is awesome.

**Comment by andyholmes** [comment]
> Looks like it has cleared up, yes — thanks!

Glad to hear it, I hope to release v7 in the next day or so with a WebExtension for Chrome and Firefox, along with all the other fixes.

> Seems even turning off the extension, completely replacing the directory, and restarting gnome-shell (I'm still running Xorg; Nvidia proprietary drivers) wasn't enough to kill it off.

That might be a bug I'll have to look into :/ The daemon is set to watch its own file and quit if it's changed, replaced or deleted to allow for upgrades and removal.

With regard to Xorg, I can tell you that's not a bad idea. Even running Gnome 3.26 I can tell you Wayland is not ready for prime-time, unless you like your popup menus squished and on the other side of the screen ;)

**Comment by ferdnyc** [comment]
> That might be a bug I'll have to look into :/ The daemon is set to watch its own file and quit if it's changed, replaced or deleted to allow for upgrades and removal.

That might be my fault. As I said I "completely replaced the directory" — by which I mean, I moved it out of the way and created a new one to unzip the current code into, so I'd be able to diff them for comparison purposes. So the old daemon's source file was still there, unchanged. Sounds like I did the one thing it _wouldn't_ notice, oops. I'll keep that in mind for the future.

**Comment by andyholmes** [comment]
> Sounds like I did the one thing it wouldn't notice, oops.

That's okay, and helpful description, I'll just set it to watch for moves as well. When you're programming for linux accounting for power-users just comes with the territory ;)

**Comment by ferdnyc** [comment]
...Though, before doing any of that, I _did_ switch the extension to Off in `gnome-tweak-tools`. Seems like that should also kill the daemon, right?

**Comment by andyholmes** [comment]
Unfortunately not, what it does do is remove the `.desktop` file and DBus `.service` file preventing it from being automatically started.

Anytime the screen locks or the desktop "state" changes in any way Gnome Shell calls `disable()` on all the extensions, that's actually why there's a separate daemon. Otherwise all the code could be in the extension instead of a separate process. This means the daemon has to ignore extension disabling, otherwise it would quit whenever the screen blanked, locked or went idle.

Compare this with the Email Notifications extension which gives you a flurry of notifications when the screen unlocks, and Dropdown Terminal which uses a daemon to keep processes running when the screen is off.

**Comment by ferdnyc** [comment]
> Anytime the screen locks or the desktop "state" changes in any way Gnome Shell calls `disable()` on all the extensions, that's actually why there's a separate daemon.

Hm, Github has neither "Wow" nor "Aha!" among its comment reactions, so I'll just register a combination of those two the old-fashioned way, with actual words.
