### ISSUE TITLE
Device icon not scaled to display density

### ISSUE THREAD

**Issue by flipflop97** [andyholmes/gnome-shell-extension-gsconnect#176]
I noticed the device icon with the battery circle on the left of each device should be twice the size as it is for me, this is caused by my display using 200% scaling. Setting scaling to 100% makes it behave like normal and setting it to 300% makes it even smaller relatively.

![screenshot from readme](https://raw.githubusercontent.com/andyholmes/gnome-shell-extension-gsconnect/master/extra/screenshot.png)  
*Big device icon (from readme)*

![screenshot](https://user-images.githubusercontent.com/13943260/44618195-ba968e80-a871-11e8-8eff-81ad941e7a13.png)  
*Small device icon (200% scaling)*

**Comment by danieldeng2** [comment]
Noticed as well. Anyone have any idea how to fix?

**Comment by danieldeng2** [comment]
This might be helpful: https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/71

**Comment by andyholmes** [comment]
For most Clutter elements this should be done automatically, but the device icon is a custom cairo surface so I'll have to make some changes to support HiDPI screens. I'm approaching the time to merge the wip-rewrite branch so this won't be done until after that.

**Comment by andyholmes** [comment]
I thought I'd just update you to let you know I'm working hard to get the rewrite in shape to merge. I'd just like to get everything major settled (like new/deprecated settings, file paths) so I can do a "feature freeze" and a release candidate (v13-RC1) soon after.

Since I don't have a HiDPI screen and emulating one is difficult, I'd appreciate help testing the extension from people that do, to make sure everything looks like it is supposed to. I was told by a Gnome dev that this is usually handled automatically at render time, but maybe there are some other exceptions where it has to be adjusted manually (like that Remote Input bug) that I can't predict.

On the upside, I might be able to use the opportunity to make the whole widget resizable in CSS, which would let themers include adjustments for their "compact" variants.

**Comment by andyholmes** [comment]
Hi, I've recently merged the rewrite and I'd like to address the HiDPI issues in GSConnect before doing a release candidate. If you have the time I'd appreciate help tracking those down and fixing them since I don't have a HiDPI screen myself.

I pushed a change that checks the scale factor before loading the device icon, and the overall size is set in CSS. I'm hoping this at least partially fixes the problem.

**Comment by danieldeng2** [comment]
Hi @andyholmes I just installed the master branch and the same problem still persists. 
![screenshot from 2018-09-22 14-37-34](https://user-images.githubusercontent.com/36489683/45917816-2e2dba80-be75-11e8-8f7f-4f47da8c9035.png)

**Comment by andyholmes** [comment]
Okay, I think I fixed it this time.

**Comment by danieldeng2** [comment]
![screenshot from 2018-09-23 19-28-43](https://user-images.githubusercontent.com/36489683/45931510-eab37900-bf66-11e8-80c3-a4d675bf59ed.png)
Comfirmed, thanks for the hard work.
