### ISSUE TITLE
unable to load up in gnome 3.30

### ISSUE THREAD

**Issue by Tids** [andyholmes/gnome-shell-extension-gsconnect#186]
GSConnect is not able to start when using the latest gnome 3.30

```
Gio.DBusError: Fehler beim Aufruf von StartServiceByName für org.gnome.Shell.Extensions.GSConnect: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.gnome.Shell.Extensions.GSConnect exited with status 1

Stack trace:
  _init@/home/fabi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:33:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _parent@resource:///org/gnome/gjs/modules/_legacy.js:39:12
  _init@/home/fabi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:695:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _init@/home/fabi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:100:23
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  buildPrefsWidget@/home/fabi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:215:23
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:92:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:244:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:398:5
  @<main>:1:43
```
is what I get

**Comment by Kerrung** [comment]
I have the same issue

**Comment by andyholmes** [comment]
I believe these issues may have been solved by @ofuangka latest contributions. Unfortunately there won't be another formal release until after v13 has been merged and stabilized. Here is a Zip built from master which may work with Gnome Shell 3.30, although I have not tested it:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2377746/gsconnect.andyholmes.github.io.zip)

**Comment by andyholmes** [comment]
@Kerrung I merged them a minute or two before I built that Zip, so if you were testing from master before you didn't have them.

One fix was for a `yield` statement in the server, and that was probably what caused the server to exit. The other was in the Preferences dialog, but I don't think you got that far since the server failed first.

Right now master has *a lot* of legacy code kept around for Ubuntu 16.04 LTS, so I expected bugs like this to come up eventually. I'm not running Gnome 3.30 yet and I've been mostly using the rewrite that doesn't include any legacy javascript so I just haven't hit any of these bugs myself.

**Comment by Nik-mmzd** [comment]
+1
Installed 3.30 fix it 4 or 5 days ago, all works fine, just forgot to say it here
Gnome-shell 3.30, gjs 1.54, Arch Linux

**Comment by Kerrung** [comment]
[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2377746/gsconnect.andyholmes.github.io.zip)
I have been using this since the first time it was published here and I still do not have any issues. Maybe there are some issues, but I have not found them yet.
@andyholmes thank you so mach!

**Comment by andyholmes** [comment]
That's good to hear, but you should thank @ofuangka who found and patched those mistakes of mine :)

Unfortunately there still won't be a formal release before the rewrite is merged, but I will link to this thread from the README since more users will likely encounter this.

**Comment by grg3** [comment]
How can I apply this fixed version for 3.30. I installed 3.30 and this is the only extension that is not working. Thanks!

**Comment by Kerrung** [comment]
@grg3 If you are an Arch Linux user try this:
[GSconnect_for_GNOME330.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2392643/GSconnect_for_GNOME330.zip)

**Comment by grg3** [comment]
Thanks!

**Comment by CBiX** [comment]
> [gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2377746/gsconnect.andyholmes.github.io.zip)

On arch this worked for me with `unzip gsconnect.andyholmes.github.io.zip -d ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/` and then restart gnome-shell. Thanks for the fix!

**Comment by tingvarsson** [comment]
Am I correct that this fix is part of the legacy branch? (at least the legacy branch seemed to work for me on 3.30)
Would you accept further PRs for the legacy branch? (remove warnings and add 3.30 as supported version in metadata)
Not sure what the intention is with v12 vs v13? And if you dont want to publish any versions to http://extensions.gnome.org before v13? Would still be clean to have it properly in the git repo until v13 is good enough.

**Comment by andyholmes** [comment]
v13 has not been released, it's just the next version that will be release, and the first of the rewrite. The rewrite branch has been merged into `master` so v12 is in it's git history. `legacy` is just a snapshot of `master` before the merge.

Officially v12 doesn't support 3.30, it wasn't tested with 3.30 so it wasn't marked as supported when it was released. You can submit pull requests for legacy if you want, but they must stay compatible with the officially supported versions.

Unfortunately your pull request to fix the ByteArray warnings is not backwards compatible with the legacy ByteArray, but I'll put a note on it about how I think it could be fixed.

**Comment by tingvarsson** [comment]
Okay good to know! I saw you merged the v13 stuff into master, any guesstimate for when it is in good enough shape? Didnt fully understand from the wiki what the state actually was for v13.
And yes, I discovered myself that the solution doesn't work on pre-3.30. Did you have an idea for a solution now already that keeps backwards compatibility? Love to hear it.

**Comment by andyholmes** [comment]
I'd say v13 it's stable for daily use, but I'm really the only one that has tested it. Usually everything always works for me, but somehow someone always hits a bug I just can't hit.

I hope to get things in basic shape in maybe a week so I can do an informal freeze and finalize translation strings and stuff. After that it'll just need help testing before I do a release, since it's a really big change.

**Comment by Kerrung** [comment]
@andyholmes but we already said that we did not find any regressions in this release.
If anyone has found any regressions in this version, then let him talk about it.

**Comment by thebitstick** [comment]
Any progress on 3.30 functionality?
Only v12 is available through extensions.gnome.org

**Comment by andyholmes** [comment]
I'm going to close this since v13 is just a few days away.
