### ISSUE TITLE
Pairing request notification window on Ubuntu 20.04 being killed by dbus monitor

### ISSUE THREAD

**Issue by truckerboy** [andyholmes/gnome-shell-extension-gsconnect#982]
Describe the bug
When a pairing request is sent from an Android 9 phone to a computer running Ubuntu 20.04 on Wayland, the notification to accept/reject the request comes up for less than a second on the computer and then disappears. This functionality used to work flawlessly in the past.
Pairing request from computer to phone still works fine.

Steps To Reproduce:
Send a pairing request from an Android 9 phone to a computer running Ubuntu 20.04 on Wayland.
The notification to accept/reject the request should comes up for less than a second on the computer and then disappear.

Expected behavior
The notification should not get "killed" automatically

System Details (please complete the following information):

    GSConnect version: 43
        Installed from: GNOME Extensions Website

    GNOME/Shell version: 3.36.3

    Distro/Release: Ubuntu 20.04.1 LTS

    Paired Device(s): LG V30, Android 9

    KDE Connect app version: 1.14.2

Relevant Log snippet from /var/log/syslog:

Sep 27 21:25:07 ubuntudesktop dbus-daemon[19009]: [session uid=1000 pid=19009] Monitoring connection :1.98 (uid=1000 pid=19751 comm="gjs /home/ubuntuuser/.local/share/gnome-shell/extension" label="unconfined") is not allowed to send messages; closing it. Please fix the monitor to not do that. (message type="error" interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.UnknownMethod" destination=":1.67")

**Comment by andyholmes** [comment]
Thanks for reporting, should be fixed in 0c677e6, ZIP available in [job artifacts](https://github.com/andyholmes/gnome-shell-extension-gsconnect/actions/runs/277514281).

**Comment by Amr-Ibra** [comment]
Would this fix be applied to a release that would still support gnome-shell 3.36? I'm asking because of Ubuntu 20.04.

**Comment by andyholmes** [comment]
It will probably work for GNOME 3.36, but there won't be any more releases with official support.

**Comment by ferdnyc** [comment]
The commit in question applies cleanly on top of `v43`, and I'm guessing several earlier versions as well. The code in those immediate areas was last touched in 2018 and 2017.

@Amr-Ibra you can update an installed `v43` by downloading the attached patch file and running the following in a shell:
```sh
cd "$HOME/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io"
patch -p2 -b < $HOME/Downloads/pairing_notification.patch.txt
```
(Obviously, you may have to adjust the path to the patch file.)

Then switch GSConnect off and on again, or log out/in, and that should do it.

[pairing_notification.patch.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/5302240/pairing_notification.patch.txt)

**Comment by mkwork** [comment]
Still reproduces at ubuntu 20.04 X11 session. I've tried to apply patch manually. I've just updated code and restarted shell. Should have I done something also?

**Comment by mkwork** [comment]
It seems to be result of some interception with "do not distrub" modes. Idk how to debug it better.

**Comment by troodonic** [comment]
Same here, notification flashes for less than half a second. Way too fast to respond.

**Comment by Devanshchowdhury2212** [comment]
Same here notificiation comes up for a second.

GSConnect: 43 (user)
Session:   x11
OS:        Ubuntu 20.04.2 LTS

**Comment by gleb-skobinsky** [comment]
Still relevant. Ubuntu 20.04.6 LTS
